#!/bin/bash
#
# Contains commands to add a new window to an existing tmux session
#
# Note that it is best to create the window in detached state (-d option) so that
# the window is complete before displaying it with select-window. tmux messes up the
# initial display if you don't.

# Set the window name to the last part of the directory path
PATHNAME=`pwd`
LABEL=`basename $PATHNAME | tr '.' '_'`

# get the current active session name (there has to be a better way than this :-/
# SESSION='tmux list-sessions -F "#{session_name}#{session_attached}" | tr -d '\n' | sed s/[a-zA-Z_-]*0// | sed s/1$//'

# Check if the window already exists, but don't stay on it so we can see the warning
# message.
tmux select-window -t $LABEL
WINDOW_EXISTS=$?

tmux select-window -n

if [ $WINDOW_EXISTS = 1 ]
then

# *************************************************************************************
# Build your window here
# *************************************************************************************
    tmux set default-path $PATHNAME
    tmux new-window -d -n $LABEL
    tmux split-window -d -h -t $LABEL
    tmux split-window -d -h -t $LABEL #'emacsclient -nw . ; bash -l'
    tmux split-window -d -v -t $LABEL
# Set the layout by hand then call tmux list-windows to get the incantation for select-layout
    tmux select-layout -t $LABEL "  67,204x64,0,0{111x64,0,0,92x64,112,0[92x30,112,0,92x22,112,31,92x10,112,54]}"
    tmux select-window -t $LABEL
    tmux send-keys -t :$LABEL.3 'ec .' C-m
    # emacs client screws up if this sleep is removed or shortened
    sleep 3
    tmux send-keys -t :$LABEL.2 'ec .' C-m
    tmux select-pane -t 2

# *************************************************************************************

else
    echo "Warning: window called $LABEL already exists"
fi
