#!/bin/bash

TME=`which tmux`
echo $LABEL
$TME split-window -d -h -t $LABEL
$TME split-window -d -v -t $LABEL
#set the layout by hand then call tmux list-windows to get the incantation for select-layout
if ! $TME select-layout -t $LABEL "5c65,204x63,0,0{111x63,0,0,92x63,112,0[92x43,112,0,92x19,112,44]}"
then
    echo "Perhaps you are running a different version of tmux? Set the layout by hand and then run tmux list-windows to get a suitable layout string for your machine. Add it in to .tmux.default"
    $TME select-layout -t $LABEL "49a1,227x84,0,0{113x84,0,0,7,113x84,114,0[113x60,114,0,6,113x23,114,61,4]}"
fi
$TME select-window -t $LABEL

$TME send-keys -t :$LABEL.1 'ec init.el' C-m
$TME send-keys -t :$LABEL.2 'ec iw-lib' C-m
# Put the cursor in pane 2 (the top right pane, running emacs client)
$TME select-pane -t 2
