#!/bin/bash
#
# This file was copied from ~/.tmux.default
#
# Contains commands to add a new window to an existing tmux session
#
# Note that it is best to create the window in detached state (-d option) so that
# the window is complete before displaying it with select-window. tmux messes up the
# initial display if you don't.

# *************************************************************************************
# Build your window here
# *************************************************************************************
tmux send-keys -t :$LABEL.1 'ec . ; bash -l' C-m
tmux split-window -d -h -t $LABEL
tmux split-window -d -v -t $LABEL
tmux send-keys -t :$LABEL.2 'ec .' C-m
#set the layout by hand then call tmux list-windows to get the incantation for select-layout
tmux select-layout -t $LABEL "5c65,204x63,0,0{111x63,0,0,92x63,112,0[92x43,112,0,92x19,112,44]}"
tmux select-window -t $LABEL

# emacs client screws up if this sleep is removed or shortened
# sleep 3

sleep 3



# Put the cursor in pane 2 (the top right pane, running emacs client)
tmux select-pane -t 1
tmux send-keys -t :$LABEL.2 M-x 'org-todo-list' C-m
# tmux send-keys -t :$LABEL.1 M-x 'org-todo-list' C-m
# *************************************************************************************
