#!/bin/bash
#
# This file was copied from ~/.tmux.default
#
# Contains commands to add a new window to an existing tmux session
#
# Note that it is best to create the window in detached state (-d option) so that
# the window is complete before displaying it with select-window. tmux messes up the
# initial display if you don't.

# *************************************************************************************
# Build your window here
# *************************************************************************************
# tmux set default-path $PATHNAME
# tmux new-window -d -n $LABEL
TME=/opt/local/bin/tmux
EMACSCLIENT=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient
echo "Running dottmux/default"
echo $LABEL
$TME split-window -d -h -t $LABEL
$TME split-window -d -v -t $LABEL "$EMACSCLIENT -nw . ; bash -l"
#set the layout by hand then call tmux list-windows to get the incantation for select-layout
if ! $TME select-layout -t $LABEL "7ef6,178x48,0,0{98x48,0,0,49,79x48,99,0[79x14,99,0,51,79x33,99,15,50]}"
then
    echo "Perhaps you are running a different version of tmux? Set the layout by hand and then run tmux list-windows to get a suitable layout string for your machine. Add it in to .tmux.default"
    $TME select-layout -t $LABEL "49a1,227x84,0,0{113x84,0,0,7,113x84,114,0[113x60,114,0,6,113x23,114,61,4]}"
fi
$TME select-window -t $LABEL
# Put the cursor in pane 2 (the top right pane, running emacs client)
# $TME select-pane -t 2
tmux send-keys -t :$LABEL.3 'ec .' C-m
tmux send-keys -t :$LABEL.1 'ec .' C-m
# *************************************************************************************
