#!/bin/bash
#
# **********************************************************
# Build your window here
# $LABEL contains the name of the tmux window being created
# **********************************************************
echo "running dottmux/startup"
LABEL=`basename $HOME`
echo "Label is: $LABEL"
tmux split-window -d -h -t :$LABEL
tmux split-window -d -v -t :$LABEL 'emacsclient -nw . ; bash -l'
#set the layout by hand then call tmux list-windows to get the incantation for select-layout
if [ $HOSTNAME == subversion.local ]
then
    tmux select-layout -t :$LABEL "5c65,204x63,0,0{111x63,0,0,92x63,112,0[92x43,112,0,92x19,112,44]}"
else
    # tmux select-layout -t :$LABEL "8995,227x84,0,0{113x84,0,0,4,113x84,114,0[113x60,114,0,6,113x23,114,61,5]}"
    tmux select-layout -t :$LABEL "bd5c,151x41,0,0{89x41,0,0,61x41,90,0[61x26,90,0,61x14,90,27]}"
fi

tmux select-window -t :$LABEL
# Put the cursor in pane 2 (the top right pane, running emacs client)
tmux select-pane -t 2
sleep 1
tmux send-keys -t :$LABEL.2 M-x 'org-todo-list' C-m
# **********************************************************
